version: "3.8"

services:
  app:
    build: .
    ports:
      - "3001:3001"
      - "8001:8001"
    volumes:
      - ./app:/app
      - app_node_modules:/app/node_modules
    command: npm run dev

volumes:
  app_node_modules:
