version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/usr/src/app
      - backend_node_modules:/usr/src/app/node_modules
    command: npm run dev

  frontend:
    build: ./frontend
    ports:
      - "8001:8001"
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    command: npm run dev

volumes:
  backend_node_modules:
  frontend_node_modules:
